services:
  mariadb:
    image: mariadb:11.3
    container_name: container-mariadb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./dados_mariadb:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/my.cnf:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  dados_mariadb:
